services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: food_delivery
      POSTGRES_USER: food_user
      POSTGRES_PASSWORD: food_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
